### ISSUE TITLE
"random" command plays only 2 songs then stop

### ISSUE THREAD

**Issue by pooh95** [kumarajith/LocalMusicBot#1]
Everything is good so far excepts for random command. When triggered, it only plays 2 random songs from local music folder and stop playing. Can you please take a look and tell me what caused this issue?

**Comment by kumarajith** [comment]
@pooh95 The dispatcher's on event functions were not being triggered after the first song was played. This issue should have affected the play command as well. Not sure why it didn't. Have fixed this in the latest commit by setting the on event callbacks for every instance of the dispatcher(after every song)
